<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" media="screen" href="../public/styles/style-admin.css"/>
    <title>Admin Panel</title>
</head>
<body>

<div class="container">
    <div class="red" id="left-column">
        <h1 id="admin-header">Admin panel</h1>
        <div class="settings">
            <a href="index.php?subview=info"><img id="admin" class="settings" src="../app/icons/admin.png"/></a>
            <img id=user" class="settings" src="../app/icons/profile-user.png"/>
            <img id="options" class="settings" src="../app/icons/gear.png"/>
            <img id="trends" class="settings" src="../app/icons/trend.png"/>
        </div>
    </div>
    <div class="green" id="right-column">
        <?php include $config['VIEW_PATH'] . 'subview' . DS .  'info.phtml'; ?>
    </div>
</body>
</html>

</body>
</html>

    </div>
</div>

</body>
</html>
