<h1 id="header">Captcha</h1>
<div class="frame" style="horiz-align: center">
    <?php
    session_start();

    if (isset($_POST['code'])) {
        if ($_POST['code'] == $_SESSION['captcha']) {
            echo "Captcha is valid";
            redirect("LoginUser.php");
        }
        else {
            echo "Captcha is invalid";
        }
    }


    $_SESSION['captcha'] = mt_rand(10000, 99999);


    function redirect($url) {
        ob_start();
        header('Location: '.$url);
        ob_end_flush();
        die();
    }
    ?>
    <form action="" method="post">
        <p>Enter this number: <?php echo $_SESSION['captcha']; ?></p>
        <p><input type="text" name="code" /></p>
        <input type="submit" value="Submit" />
    </form>
</div>