
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div class="row">
<div class="left-column">
    <div class="card">
        <?php
        echo selectPosts();
        ?>
    </div>
    <div id="post-popup">
        <div class="popup-header">
            <p class="popup-header">Create a new post</p>
            <?php
            $image = displayImage($config['ICONS_PATH'] . 'remove-button.png', true);
            echo "<img src = 'data:image/png;base64,$image' id='commentary-hidden-button' onclick='closeForm()'/>";
            ?>
        </div>
        <form method="POST">
            <?php
                    $action = isset($_SESSION['user']) ?  "" :   "<div class='popup-cards'>
                <p>Author</p>
                <input type='text' name='author' id='author' class='inputs' required/>
            </div>";
                    echo $action;

            ?>
            <div class="popup-cards">
                <p>Title</p>
                <input type="text" name="title" id="title" class="inputs" required/>
            </div>
            <div class="popup-cards">
                <p>Post message</p>
                <textarea id="post" class="inputs" name="post" cols="1000" rows="10" required></textarea>
            </div>
            <div class="popup-cards">
                <input type="submit" value="add" id="post-button" name="add"/>
            </div>
            <div class="popup-cards" id="right-corner">
                <?php
                addNewPost();
                ?>
            </div>
        </form>
    </div>
    <input type="button" value="Add a new post" id="add-new-post" onclick="openForm()"/>
    <script type="text/javascript">
        function openForm() {
            document.getElementById("post-popup").style.display = "block";
        }

        function closeForm() {
            document.getElementById("post-popup").style.display = "none";
        }
    </script>
</div>
<div class="right-column">
    <div class="right-card">
        <h2 class="article-headers">About me</h2>
        <hr>
        <p class="about-author-description">I am a student of Computer Science at the University of Silesia</p>
    </div>
    <div class="right-card">
        <h2 class="article-headers">Quadratic Equations</h2>
        <hr>
        <form action="Index.php" method="POST">
            <p>A: <input type="number" name="A" class="inputs"/></p>
            <p>B: <input type="number" name="B" class="inputs"/></p>
            <p>C: <input type="number" name="C" class="inputs"/></p>
            <input type="submit">
        </form>

        <?php
        if (isset($_POST['A']) and isset($_POST['B']) and isset($_POST['C'])) {
            $A = $_POST['A'];
            $B = $_POST['B'];
            $C = $_POST['C'];

            echo '<hr/>';
            quadraticEquation($A, $B, $C);
        }

        ?>
    </div>
    <div class="right-card">
        <h2 class="article-headers">TIWP lab exercises</h2>
        <hr>
        <li class="TWI-list"><a href="TIWP_LAB/Canvas/Canvas.php">Canvas</a></li>
        <li class="TWI-list"><a href="TIWP_LAB/AudioVideo/VideoAudio.php">Audio & Video</a></li>
        <li class="TWI-list"><a href="TIWP_LAB/FormHTML4/FormHTML4.php">Form HTML4</a></li>
        <li class="TWI-list"><a href="TIWP_LAB/FormHTML5/FormHTML5.php">Form HTML5</a></li>
        <li class="TWI-list"><a href="TIWP_LAB/AJAX-XML/Ajax-XML.php">AJAX-XML</a></li>
        <li class="TWI-list">jQuery</li>
        <li class="TWI-list">Snake jQuery</li>
        <li class="TWI-list">Project</li>
    </div>
</div>
</div>




</body>
</html>
