<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div class="row">
    <div class="left-column">
        <?php
        echo selectPosts();
        ?>
        <div id="post-popup">
            <div class="popup-header">
                <p class="popup-header">Create a new post</p>
                <?php
                $image = displayImage($config['ICONS_PATH'] . 'remove-button.png', true);
                echo "<img src = 'data:image/png;base64,$image' id='commentary-hidden-button' onclick='closeForm()'/>";
                ?>
            </div>
            <form method="POST">
                <?php
                $action = isset($_SESSION['user']) ? "" : "<div class='popup-cards'>
                <p>Author</p>
                <input type='text' name='author' id='author' class='inputs' required/>
            </div>";
                echo $action;
                ?>
                <div class="popup-cards">
                    <p>Title</p>
                    <input type="text" name="title" id="title" class="inputs" required/>
                </div>
                <div class="popup-cards">
                    <p>Post message</p>
                    <textarea id="post" class="inputs" name="post" cols="1000" rows="10" required></textarea>
                </div>
                <div class="popup-cards">
                    <input type="submit" value="add" id="post-button" name="add"/>
                </div>
                <div class="popup-cards">
                    <?php
                    addNewPost();
                    ?>
                </div>

            </form>
        </div>
        <input type="button" value="Add a new post" id="add-new-post" onclick="openForm()"/>
        <script type="text/javascript">
            function openForm() {
                document.getElementById("post-popup").style.display = "block";
            }

            function closeForm() {
                document.getElementById("post-popup").style.display = "none";
            }
        </script>

        <div class="pagination">
            <table class="next-page">
                <?php
                $image = displayImage($config['ICONS_PATH'] . 'left-arrow.png', true);
                if($_SESSION['pageNow'] != 1){
                    $var = "?pagination=" . ($_SESSION['pageNow'] - 1);
                }
                else{
                    $var = "?pagination=" . ($_SESSION['pageNow']);
                }
                echo "<a href='$var'><img src = 'data:image/png;base64,$image' class='pag-rows' id='left-arrow-pag'/></a>"; ?>
                <?php
                for ($i = 1; $i <= $_SESSION['amountOfPages']; $i++) {
                    printf("<a href='?pagination=%u' class='pag-rows'>%u</a>",
                    $i, $i);
                }
                ?>
                <?php
                $image = displayImage($config['ICONS_PATH'] . 'right-arrow.png', true);
                $var = "?pagination=" . ($_SESSION['pageNow'] + 1);
                if($_SESSION['pageNow'] != $_SESSION['amountOfPages']){
                    $var = "?pagination=" . ($_SESSION['pageNow'] + 1);
                }
                else{
                    $var = "?pagination=" . ($_SESSION['pageNow']);
                }
                echo "<a href='$var'><img src = 'data:image/png;base64,$image' class='pag-rows' id='right-arrow-pag'/></a>"; ?>
            </table>
        </div>
    </div>
    <div class="right-column">
        <div class="right-card">
            <h2 class="article-headers">About me</h2>
            <hr>
            <p class="about-author-description">I am a student of Computer Science at the University of Silesia</p>
        </div>
        <div class="right-card">
            <h2 class="article-headers">Quadratic Equations</h2>
            <hr>
            <form action="Index.php" method="POST">
                <p>A: <input type="number" name="A" class="quadratic-equ-input"/></p>
                <p>B: <input type="number" name="B" class="quadratic-equ-input"/></p>
                <p>C: <input type="number" name="C" class="quadratic-equ-input"/></p>
                <button type="button" onclick="quadraticEquation(3,2,1)">Solve</button>
            </form>
            </hr>
            <p id="equation-output"></p>
            <script>
                function quadraticEquation(A, B, C){
                    window.func = arg => console.log('=\\');
                    $.ajax({
                        type: 'POST',
                        url: '../app/lib/math.php',
                        data: {action: 'math', 'A=' + A + "B=" + B + "C=" + C}
                        success: function(data){
                            console.log(data);
                            $('#equation-output').text(data)
                            alert(data);
                            console.log(data);
                         }
                    });
                }
            </script>

        </div>
        <div class="right-card">
            <h2 class="article-headers">TIWP lab exercises</h2>
            <hr>
            <li class="TWI-list"><a href="TIWP_LAB/Canvas/Canvas.php">Canvas</a></li>
            <li class="TWI-list"><a href="TIWP_LAB/AudioVideo/VideoAudio.php">Audio & Video</a></li>
            <li class="TWI-list"><a href="TIWP_LAB/FormHTML4/FormHTML4.php">Form HTML4</a></li>
            <li class="TWI-list"><a href="TIWP_LAB/FormHTML5/FormHTML5.php">Form HTML5</a></li>
            <li class="TWI-list"><a href="TIWP_LAB/AJAX-XML/Ajax-XML.php">AJAX-XML</a></li>
            <li class="TWI-list">jQuery</li>
            <li class="TWI-list">Snake jQuery</li>
            <li class="TWI-list">Project</li>
        </div>
    </div>
</div>

<footer class="footer">
    <p id="footer-author">Created by Patryk Kuszneruk. spec ISI</p>

    <?php
    $image = displayImage($config['ICONS_PATH'] . 'chat.png', true);
    echo "<a href='index.php?page=form' class='link-chat'>";
    echo "Contact me";
    echo "<img src = 'data:image/png;base64,$image'class='chat'/>";
    echo "</a>";
    ?>
    <div class="footer-icons">
        <?php
        $image = displayImage($config['ICONS_PATH'] . 'facebook.png', true);
        echo "<a href='https://www.facebook.com/patryk.kuszneruk'>";
        echo "<img src = 'data:image/png;base64,$image'class='footer-icons'/>";
        echo "</a>";
        $image = displayImage($config['ICONS_PATH'] . 'github.png', true);
        echo "<a href='https://github.com/pkuszn'>";
        echo "<img src = 'data:image/png;base64,$image'class='footer-icons'/>";
        echo "</a>";
        $image = displayImage($config['ICONS_PATH'] . 'linkedin.png', true);
        echo "<a href='https://www.linkedin.com/in/patryk-kuszneruk-521b7a1bb/'>";
        echo "<img src = 'data:image/png;base64,$image' class='footer-icons' />";
        echo "</a>";
        ?>
    </div>
</footer>

</body>
</html>
