<div>
    <button style="margin: 0 auto; display: block;" id="test-button" type="button">Test</button>
    <h1 id="test-p"></h1>
    <script type="text/javascript">
        $('button').click(function () {
            $.get('../app/model/test.php', function (data) {
                $('#test-p').html(data);
            });
        });
    </script>
</div>
<div>
    <?php
    print_r($_SESSION);
    ?>

</div>