<head>
    <link rel="stylesheet" href="styles/style-admin.css" />
</head>
<body>
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" type="text/css" media="screen" href="../public/styles/style-admin.css" />
        <title>Admin Panel</title>
    </head>
    <body>
        <div class="container">
            <div class="red" id="left-column">
                <h1 id="admin-header">User panel</h1>
                <div class="settings">
                    <img id="admin" class="settings" src="../app/icons/admin.png" />
                    <img id=user" class="settings" src="../app/icons/profile-user.png" />
                    <img id="options" class="settings" src="../app/icons/gear.png" />
                    <img id="trends" class="settings" src="../app/icons/trend.png" />
                </div>
                <script type="javascript">
            $(document).ready(function(){
                $(".settings").click(function () {
                    alert('in progress..')
                });
            });
        </script>
            </div>
            <h1 id="user-panel-label">Account settings</h1>
            <div class="green" id="right-column">
                <div>
                </div>
                <div class="user-settings">
                    <li class="user-data-template">
                        Avatar
                    </li>
                    <li class="user-data-template">
                        Name
                    </li>
                    <li class="user-data-template">
                        Username
                    </li>
                    <li class="user-data-template">
                        Contact
                    </li>
                    <li class="user-data-template">
                        Password
                    </li>
                    <li class="user-data-template">
                        Access
                    </li>
                    <li class="user-data-template">
                        Amount of posts
                    </li>
                    <li class="user-data-template">
                        Date account created
                    </li>
                    <li class="user-data-template">
                        Birthday
                    </li>
                    <li class="user-data-template">
                        City
                    </li>
                </div>
                <div class="user-settings right-side">
                    <li class="user-data-template">
                        <?php
                        require_once ($_SERVER['DOCUMENT_ROOT'] . '/blog/BlogFromScratch/app/lib/upload.php');
                        $img = $_SERVER['DOCUMENT_ROOT'] . '/blog/BlogFromScratch/app/lib/uploads/' . getFilename($_SESSION['id']);
                        $image = displayImage($img, true);
                        $action = ($_SESSION['id'] == null) ? '-' : "<img src = 'data:image/png;base64,$image' id='avatar-user-panel'/>";
                        echo $action;
                        ?>
                    </li>
                    <li class="user-data-template">
                        <?php echo $_SESSION['user'] //required  ?>
                    </li>
                    <li class="user-data-template">
                        <?php
                        $action = ($_SESSION['first_name'] == null) ? '-' : $_SESSION['first_name'];
                        $action2 = ($_SESSION['last_name'] == null) ? '-' : $_SESSION['last_name'];
                        echo $action . $action2;
                        ?>
                    </li>
                    <li class="user-data-template">
                        <?php echo $_SESSION['email'] //required  ?>

                    </li>
                    <li class="user-data-template">
                        <?php echo $_SESSION['pass'] //required  ?>

                    </li>
                    <li class="user-data-template">
                        <?php echo $_SESSION['access'] //required  ?>
                    </li>
                    <li class="user-data-template">
                        <?php
                        $action = ($_SESSION['access'] == 0) ? '-' : $_SESSION['access'];
                        echo $action;
                        ?>
                    </li>
                    <li class="user-data-template">
                        <?php echo $_SESSION['date-created'] //required  ?>
                    </li>
                    <li class="user-data-template">
                        <?php
                        $action = ($_SESSION['birth_date'] == null) ? '-' : $_SESSION['birth_date'];
                        echo $action;
                        ?>
                    </li>
                    <li class="user-data-template">
                        <?php
                        $action = ($_SESSION['city'] == null) ? '-' : $_SESSION['city'];
                        echo $action;
                        ?>
                    </li>
                </div>
            </div>
        </div>
    </body>
    </html>
</body>
</html>