<h1 id="admin-header">Users</h1>
<?php
displayUsersWithUnknownAccess();
?>
<script type="text/javascript">
    $(document).ready(function(){
        $(".userID").click(function () {
            if (confirm("Are you sure to authorize the user?") == true) {
                var userData = $(this).attr("alt");
                $.ajax({
                    type: "POST",
                    url: '../app/model/admin.php',
                    data: {userID: userData, functionDesc: 'privileges'},
                    cache: false,
                    success: function (response) {
                        setInterval(refreshPage(), 5000);
                    }
                });
                alert(userData);
            }
        });
    });
    function refreshPage() {
        location.reload(true);
    }
</script>