<script type="text/javascript">
    $(document).ready(function () {
        $('.add-comment-button').on('click', function () {
            var postID = $(this).attr("alt");
            var message = $(this).siblings('textarea').val();
            var author = $(this).siblings('input').val();
            $.ajax({
                type: "POST",
                url: '../app/model/home.php',
                data: {postID: postID, message: message, author: author, functionName: 'insertComments'},
                cache: false,
                success: function (response) {
                    setInterval(refreshPage(), 5000);
                }
            });
        });

    });

    function refreshPage() {
        location.reload(true);
    }
</script>
